syntax = "proto3";

package payment.v1;

import "google/protobuf/timestamp.proto";


option go_package = "github.com/Bleuble/my-grpc-generated/payment/v1;paymentv1";

service PaymentService {
  rpc ProcessPayment(PaymentRequest) returns (PaymentResponse);
  rpc ListPayments(ListPaymentsRequest) returns (ListPaymentsResponse);
}

message ListPaymentsRequest {
  string status = 1; // "Authorized" or "Declined"
}

message ListPaymentsResponse {
  repeated PaymentResponse payments = 1;
}

message PaymentRequest {
  string order_id = 1;
  double amount = 2;
  string currency = 3;
  string customer_email = 4;
}

message PaymentResponse {
  string transaction_id = 1;
  string status = 2;
  google.protobuf.Timestamp processed_at = 3;
}
